
%%% ==============================================================================
% 	Purpose: 
%	This function replots current iteration and hides previous iteration.
%%% ==============================================================================


function [TempvTimeChildren, ...
    TempvTauChildren, ...
    TempvBullFuncChildren, ...
    TimeShiftChildren, ...
    CTempvCtimeChildren, ...
    MisfitvTimeShiftChildren, ...
    CTempv1_CTimeChildren, ...
    TempvTimeShiftChildren ...
    ] = IteratePlots(axes_TempvTime, ...
    axes_TempvTau, ...
    axes_TempvBullFunc, ...
    axes_TimeShift, ...
    axes_CTempvCtime, ...
    axes_MisfitvTimeShift, ...
    axes_CTempv1_CTime, ...
    axes_TempvTimeShift, ...
    MaxNumberOfIterations, ...
    Iteration)

% Save axes children
% -------------------
 TempvTimeChildren = axes_TempvTime.Children;
 TempvTauChildren = axes_TempvTau.Children;
 TempvBullFuncChildren = axes_TempvBullFunc.Children;
 TimeShiftChildren = axes_TimeShift.Children;

 CTempvCtimeChildren = axes_CTempvCtime.Children;
 MisfitvTimeShiftChildren = axes_MisfitvTimeShift.Children;
 CTempv1_CTimeChildren = axes_CTempv1_CTime.Children;
 TempvTimeShiftChildren = axes_TempvTimeShift.Children;


